### ISSUE TITLE
oom error

### ISSUE THREAD

**Issue by zoepiran** [google-research/ott#27]
hi,

Please excuse me in advance if there is a basic mis-usage in the attached code/setting.  
In this [drive](https://drive.google.com/drive/folders/1S9yCVMDaCdIZWuQwG7fIjYxox-ynFkzp?usp=sharing) you can find the following folders:
[1] `code`: two code files (differing in the cost object type, in 'gwlr.py' costs are `pointclouds`  and in `gwlr_geom,py` we use general `Geometry`) which can reproduce our `oom` errors we encounter running on GPUs. 
** we noticed that changing `alpha` to `0.75` we are able refrain from `oom` using `low rank` however while geometry run returned quickly the pointcloud calculation took >2 hrs.
[2] `logs`: 4 log-files documenting the errors in regular (`quad`) and low rank (`lr`) runs using `pointcloud` costs and `Geometry` (`geom`) objects.
[3] `data`: The data to run the code.
We realize it may be that the data is too large but will be grateful for your input. 
(I am still trying to set-up different mem. allocation on our GPUs that may allow this)

Thank you in advance :)

**Comment by olivierteboul** [comment]
Hi @zoepiran , would you mind shrinking down your code to a minimal example and paste it here? It would be much easier to track down the bug. Also I believe you can probably replace your data by random data, if the error is memory, the problem most likely linked to the amount of data, not the actual values.

**Comment by marcocuturi** [comment]
Hi Zoe, I agree with Olivier that a working colab should be easier for us to parse.

In the meantime, maybe you could help me parse the log files. In `quad-0.001-0.75-pointcloud.log` I see

```
Traceback (most recent call last):
  File "/cs/labs/mornitzan/zoe.piran/research/projects/moscot_framework_analysis/notebooks/seqfish/gwlr.py", line 127, in <module>
    gwlr(args)
  File "/cs/labs/mornitzan/zoe.piran/research/projects/moscot_framework_analysis/notebooks/seqfish/gwlr.py", line 78, in gwlr
    ot_quad = solve(args.alpha, C1=Cexp_geom, C2=Cphys_geom, M=M_geom, epsilon=args.epsilon)
```

but I can't see immediately where the `Cexp_geom` and `Cphys_geom` geometry objects are instantiated?

**Comment by zoepiran** [comment]
Here;
this should do:

`
import scanpy as sc
import ott

epsilon = 1e-3
alpha = 0.5
rank_order = 6
gamma = 1

adata_sq = sc.read('~/adata_sq_processed.h5ad')
adata_sc = sc.read(~/adata_processed.h5ad')

Cphys_geom = ott.geometry.pointcloud.PointCloud(adata_sq.obsm['spatial'])
Cexp_geom = ott.geometry.pointcloud.PointCloud(adata_sc.obsm['X_scvi'])

adata_sc_tmp = adata_sc[:, adata_sc.var['marker']]
adata_spatial_tmp = adata_sq[:, adata_sc_tmp.var['SYMBOL'].astype(str).values]
M_geom = ott.geometry.pointcloud.PointCloud(adata_sc_tmp.X.toarray(), adata_spatial_tmp.X.toarray(), epsilon=epsilon)

Cphys_geom.rescale_cost(1 / Cphys_geom.mean_cost_matrix)
Cexp_geom.rescale_cost(1 / Cexp_geom.mean_cost_matrix)
M_geom.rescale_cost(1 / M_geom.mean_cost_matrix)

ot_prob = ott.core.quad_problems.QuadraticProblem(geom_xx=C1,
                                                              geom_yy=C2,
                                                              geom_xy=M,
                                                              fused_penalty=(1 - alpha) / alpha) 
if type =='lr':
         n, m = M_geom.shape
         rank = int(min(n, m) / rank_order)
         solver = ott.core.gromov_wasserstein.GromovWasserstein(rank=rank, gamma=gamma)
else:
         solver = ott.core.gromov_wasserstein.GromovWasserstein(epsilon=epsilon)

ot_gw = solver(ot_prob)`

**Comment by zoepiran** [comment]
its missing in the `log` files. will open a colab real quick (based on this [nb](https://github.com/theislab/moscot_framework_analysis/blob/analysis/spatial_impute/notebooks/seqfish/ZP_2022-01-11_seqfish_spatial-mapping.ipynb))

**Comment by zoepiran** [comment]
I tried removing it and it didn;t change the behavior - the failure is later in solve.

**Comment by zoepiran** [comment]
Excuse my delay; created the following [colab](https://colab.research.google.com/drive/1l_Cgr0L-3Jkyi73ZHdSIRn3e-p-IWJWF?usp=sharing)
@olivierteboul regarding general random data - i agree and we could do general benchmarking experiments to test maximal inputs but i assume its best to verify all funcs are acting properly.
