### ISSUE TITLE
Reverse-mode differentiation for grad of Sinkhorn

### ISSUE THREAD

**Issue by ersisimou** [google-research/ott#7]
Hello,

Given JAX's concept of composable function transformations, it would be great if the grad function of Sinkhorn could also be differentiated with reverse mode. 
However, given the fact that the current implementation of the Sinkhorn loop uses jax.lax.while_loop (which is only fwd-mode-differentiable), this is not possible. 
It would really be helpful if a solution could be offered for that. Perhaps with jax.lax.scan and in the lines of [this](https://github.com/google/jax/discussions/3850#discussioncomment-45954) ?

Any solution to that would be strongly appreciated, as currently it is not possible to jit the grad of Sinkhorn and do automatic differentation. The only solution to my understanding is to let it unjitted and run in op-by-op mode.

Thanks in advance.

**Comment by marcocuturi** [comment]
Hi Effrosyni,

Thanks for your comment! Happy to help.

> Given JAX's concept of composable function transformations, it would be great if the grad function of Sinkhorn could also be differentiated with reverse mode.

Can you be more specific on what you would like to differentiate? sinkhorn outputs 5 variables, essentially the argmax's ``f`` and ``g``, ``reg_ot_cost``, ``errors`` and a convergence flag. ``f``, ``g`` and ``reg_ot_cost``should all be differentiable w.r.t ``a``, ``b`` and whatever is in ``geom``. For ``f`` and ``g`` that would be a Jacobin, for ``reg_ot_cost`` that would be a gradient. There are a few examples of this in the [tests](https://github.com/google-research/ott/blob/master/tests/core/sinkhorn_differentiability_test.py).

> However, given the fact that the current implementation of the Sinkhorn loop uses jax.lax.while_loop (which is only fwd-mode-differentiable), this is not possible.

Not exactly, as we wrap the while_loop around a ``fixed_iter_loop`` that does checkpointing to avoid the issue you refer to.

To summarize, we use two ways to differentiate, either with ``implicit_differentiation`` of not. While we recommend using ``implicit_differentiation=True`` (which computes VJP's by inverting a linear system), when setting that ``False``, everything is backpropped thanks to the custom rules VJP rules for ``fixed_iter_loop``.

> It would really be helpful if a solution could be offered for that. Perhaps with jax.lax.scan and in the lines of this ?

scan would remove the option to check for tolerance, so we thought this would not be a good option. Do you have an example where calling grad or jacrev on outputs of sinkhorn fails?

> Any solution to that would be strongly appreciated, as currently it is not possible to jit the grad of Sinkhorn and do automatic differentation. The only solution to my understanding is to let it unjitted and run in op-by-op mode.

As shown in the tests, it should work as it is, either in implicit diff or not!

Thanks a lot again for your interest and for your feedback as an early adopter of this!

**Comment by ersisimou** [comment]
Hi and many thanks for the response!

Yes, in fact I have been able to differentiate sinkhorn both with implicit differentiation and backprop w.r.t. both histograms and geometry. I have had no issues with calling grad on sinkhorn outputs. (btw thanks for sharing the tests on the repo-they helped)

What I was referring to was the following:

In the case where I define a network (e.g. with FLAX) and one of my layers (functions in terms of JAX) is:

 (curr_obj, aux), x1_grad = reg_ot_and_grad(z1, a1, z2, a2, epsilon)

where:

 reg_ot_and_grad = jax.jit(jax.value_and_grad(loss, (0), has_aux=True))

with loss the out.reg_ot_cost of your Sinkhorn function.

During training I would like to differentiate the reg_ot_and_grad function. However, this is not possible if I jit the jax.value_and_grad function. It is only possible if I leave it unjitted.

I understand that jax.lax.scan could only terminate with maximum number of iterations (and no criteria w.r.t. convergence of marginals). But maybe the gain (in terms of time for execution) of running the jitted version could compensate for a large maximum iterations stopping criterion of jax.lax.scan?

**Comment by marcocuturi** [comment]
Thanks for sharing this! I think I have a better idea of what you are trying to achieve but I am not sure I follow everything.

> During training I would like to differentiate the reg_ot_and_grad function. However, this is not possible if I jit the jax.value_and_grad function. It is only possible if I leave it unjitted.

The issue arises because you want to differentiate *again* reg_ot_and_grad ? Or is only that
``reg_ot_and_grad = jax.value_and_grad(loss, (0), has_aux=True)`` works, whereas
``reg_ot_and_grad = jax.jit(jax.value_and_grad(loss, (0), has_aux=True))``
does not?

**Comment by ersisimou** [comment]
The issue arises when I want to differentiate again reg_ot_and_grad. What I would like to do (during training) is differentiate the grad of Sinkhorn.

reg_ot_and_grad = jax.value_and_grad(loss, (0), has_aux=True)
and 
reg_ot_and_grad = jax.jit(jax.value_and_grad(loss, (0), has_aux=True))

work fine.

**Comment by ersisimou** [comment]
However, differentiating again reg_ot_and_grad = jax.value_and_grad(loss, (0), has_aux=True) works whereas differentiating again reg_ot_and_grad = jax.jit(jax.value_and_grad(loss, (0), has_aux=True)) does not and leads to:

ValueError: Reverse-mode differentiation does not work for lax.while_loop or lax.fori_loop. Try using lax.scan instead.

**Comment by marcocuturi** [comment]
Ok, I think I got it then! thanks for explaining. 

So to get more context, you would like to compute (for instance) the Hessian of ``reg_ot_cost`` w.r.t.  ``a`` or ``b`` or others, right?

If you can share a more detailed trace that would be great. Do you see this error using ``implicit_differentiation=True`` ? Somewhat a call to differentiating the outputs of sinkhorn again with ``implicit_differentiation`` should try to differentiating through the ``cg`` iterations, but to tell you the truth I haven't tested it (as you can probably see it in the tests we only tested first order :) )

Anyway, I think what you are suggesting is switching to scan in the outer loop of ``fixed_iter_loop``. Maybe we can do this by changing a bit the way body_fun does (or does not) compute changes. Happy to take a look at this

**Comment by ersisimou** [comment]
Yes, exactly! I believe that scan in the outer loop of fixed_iter_loop should fix this. I look forward to your update!

 
I get the same error both for ``implicit_differentiation=True" and ``implicit_differentiation=False"


The trace is the following:

Traceback (most recent call last):
  File "/home/simou/OTT/train_no_pad.py", line 289, in <module>
    app.run(main)
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/simou/OTT/train_no_pad.py", line 282, in main
    train(FLAGS.data_path, FLAGS.master_csv_path, FLAGS.split_path,
  File "/home/simou/OTT/train_no_pad.py", line 216, in train
    (loss, acc), grad = compute_loss_fn(params, graph, label)
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 139, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/api.py", line 815, in value_and_grad_f
    g = vjp_py(np.ones((), dtype=dtype))
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/api.py", line 1798, in _vjp_pullback_wrapper
    ans = fun(*args)
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/interpreters/ad.py", line 121, in unbound_vjp
    arg_cts = backward_pass(jaxpr, consts, dummy_args, cts)
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/interpreters/ad.py", line 215, in backward_pass
    cts_out = get_primitive_transpose(eqn.primitive)(
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/interpreters/ad.py", line 542, in call_transpose
    out_flat = primitive.bind(fun, *all_args, **new_params)
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/core.py", line 1402, in bind
    return call_bind(self, fun, *args, **params)
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/core.py", line 1393, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/core.py", line 1405, in process
    return trace.process_call(self, fun, tracers, params)
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/core.py", line 600, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/interpreters/xla.py", line 576, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/linear_util.py", line 260, in memoized_fun
    ans = call(fun, *args)
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/interpreters/xla.py", line 652, in _xla_callable
    jaxpr, out_avals, consts = pe.trace_to_jaxpr_final(fun, abstract_args, transform_name="jit")
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1209, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1188, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/interpreters/ad.py", line 215, in backward_pass
    cts_out = get_primitive_transpose(eqn.primitive)(
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/interpreters/ad.py", line 542, in call_transpose
    out_flat = primitive.bind(fun, *all_args, **new_params)
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/core.py", line 1402, in bind
    return call_bind(self, fun, *args, **params)
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/core.py", line 1393, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/core.py", line 1405, in process
    return trace.process_call(self, fun, tracers, params)
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1061, in process_call
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(f, self.main, in_avals)
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 1188, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/linear_util.py", line 166, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/interpreters/ad.py", line 218, in backward_pass
    cts_out = get_primitive_transpose(eqn.primitive)(cts_in, *invals,
  File "/opt/anaconda3/envs/simou_jax-version5/lib/python3.8/site-packages/jax/_src/lax/control_flow.py", line 539, in _while_transpose_error
    raise ValueError("Reverse-mode differentiation does not work for "
ValueError: Reverse-mode differentiation does not work for lax.while_loop or lax.fori_loop. Try using lax.scan instead.

**Comment by ersisimou** [comment]
@marcocuturi thanks so much for your great interaction through the issues! It is truly appreciated.
I couldn't wait to respond to your good news! 
I will close this issue, but I might come back with a comment when I will look into it carefully :).
Thanks again!

**Comment by ersisimou** [comment]
@marcocuturi thanks again for looking into this issue and for incorporating modifications to enable the computation of higher order gradients in your latest release.

Unfortunately though, my issue still exists. I share below code for training a network with haiku that reproduces my error. I just want to highlight that what this network is learning is not intended to make any sense (and I am pretty sure it wouldn't even train), it only serves the purpose of reproducing my code error. 

You will see that when computing the gradient of Sinkhorn with ```implicit_differentiation=True``` and ```use_danskin=False``` or with ```implicit_differentiation=False``` one gets the error ```ValueError: Reverse-mode differentiation does not work for lax.while_loop or lax.fori_loop. Try using lax.scan instead.```. The only case where this does not happen is when ```implicit_differentiation=True``` and ```use_danskin=True```. 

```
import os
import functools
from absl import app
import haiku as hk
import jax
import jax.numpy as jnp
from jax import random
import optax
from ott.core import sinkhorn
from ott.geometry import pointcloud
from jax.numpy.linalg import norm

# Set environment variables
os.environ['XLA_FLAGS'] = '--xla_gpu_cuda_data_dir=/usr/local/cuda'
os.environ['CUDA_VISIBLE_DEVICES'] = '1'
os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] = 'False'

# dimensions of pointclouds
n = 10
m = 5

rng = random.PRNGKey(0)
rngs = random.split(rng, 6)

# create a dataset of one sample with the positions of fist pointcloud before linear transformation
my_dataset = random.uniform(rngs[0], (n, 1))

# positions of second pointcloud
y = random.uniform(rngs[1], (m, 1))

# histograms
a = random.uniform(rngs[2], (n,)) + .1
b = random.uniform(rngs[3], (m,)) + .1
a = a / jnp.sum(a)
b = b / jnp.sum(b)

# entropy reg.
epsilon = 0.1


def loss(x1, a1, y1, b1, epsilon1):
  geom = pointcloud.PointCloud(x1, y1, epsilon=epsilon1)
  out = sinkhorn.sinkhorn(geom, a1, b1, lse_mode=True, implicit_differentiation=True, use_danskin=False, linear_solve_kwargs={'ridge_kernel': 1.2e-4})
  # out = sinkhorn.sinkhorn(geom, a1, b1, lse_mode=True, implicit_differentiation=True, use_danskin=True, linear_solve_kwargs={'ridge_kernel': 1.2e-4})
  # out = sinkhorn.sinkhorn(geom, a1, b1, lse_mode=True, implicit_differentiation=False)
  return out.reg_ot_cost, (out.f, out.g, out.converged, out.errors)


reg_ot_and_grad = jax.value_and_grad(loss, (0), has_aux=True)


def net_fn(x: jnp.ndarray) -> jnp.ndarray:
  # transform linearly the positions of first pointcloud
  x_transf = hk.Linear(1)(x)
  # compute gradient of Sinkhorn wrt transfomed positions of first pontcloud
  (ot_cost, aux), x1_grad = reg_ot_and_grad(x_transf, a, y, b, epsilon)
  return x1_grad


def compute_loss(params, x1, my_net):
  x = my_net.apply(params, x1)
  loss = norm(x)
  return loss


def train(epochs, my_dataset):

  # Transform impure net_fn to pure function
  net = hk.without_apply_rng(hk.transform(net_fn))

  # initialize network params
  params = net.init(random.PRNGKey(42), random.uniform(rngs[4], (n, 1)))

  # Initialize the optimizer.
  opt_init, opt_update = optax.adam(1e-4)

  opt_state = opt_init(params)

  compute_loss_fn = functools.partial(compute_loss, my_net=net)

  compute_loss_fn = jax.jit(jax.value_and_grad(compute_loss_fn))

  for epoch in range(epochs):
    loss, grad = compute_loss_fn(params, my_dataset)
    print(loss)
    updates, opt_state = opt_update(grad, opt_state, params)
    params = optax.apply_updates(params, updates)


def main(_):
  train(epochs=1, my_dataset=my_dataset)

if __name__ == '__main__':
  app.run(main)

```

Finally, I share below a trace that goes through the ott code. What do you think? Am I missing something? Do you have any pointers as to how I can resolve this?

 File "/home/usergpu/anaconda3/envs/jax_ott_latest/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/usergpu/anaconda3/envs/jax_ott_latest/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/usergpu/Documents/OTT_flow/second_order_reverse.py", line 91, in main
    train(epochs=1, my_dataset=my_dataset)
  File "/home/usergpu/Documents/OTT_flow/second_order_reverse.py", line 84, in train
    loss, grad = compute_loss_fn(params, my_dataset)
  File "/home/usergpu/Documents/OTT_flow/second_order_reverse.py", line 61, in compute_loss
    x = my_net.apply(params, x1)
  File "/home/usergpu/anaconda3/envs/jax_ott_latest/lib/python3.8/site-packages/haiku/_src/transform.py", line 202, in apply_fn
    return f.apply(params, None, *args, **kwargs)
  File "/home/usergpu/anaconda3/envs/jax_ott_latest/lib/python3.8/site-packages/haiku/_src/transform.py", line 126, in apply_fn
    out, state = f.apply(params, {}, *args, **kwargs)
  File "/home/usergpu/anaconda3/envs/jax_ott_latest/lib/python3.8/site-packages/haiku/_src/transform.py", line 357, in apply_fn
    out = f(*args, **kwargs)
  File "/home/usergpu/Documents/OTT_flow/second_order_reverse.py", line 56, in net_fn
    (ot_cost, aux), x1_grad = reg_ot_and_grad(x_transf, a, y, b, epsilon)
  File "/home/usergpu/Documents/OTT_flow/second_order_reverse.py", line 43, in loss
    out = sinkhorn.sinkhorn(geom, a1, b1, lse_mode=True, implicit_differentiation=True, use_danskin=False, linear_solve_kwargs={'ridge_kernel': 1.2e-4})
  File "/home/usergpu/anaconda3/envs/jax_ott_latest/lib/python3.8/site-packages/ott/core/sinkhorn.py", line 242, in sinkhorn
    return call_to_sinkhorn(geom, a, b, tau_a, tau_b, threshold, norm_error,
  File "/home/usergpu/anaconda3/envs/jax_ott_latest/lib/python3.8/site-packages/ott/core/sinkhorn.py", line 319, in _sinkhorn
    f, g, errors = iteration_fun(tau_a, tau_b, inner_iterations, min_iterations,
  File "/home/usergpu/anaconda3/envs/jax_ott_latest/lib/python3.8/site-packages/ott/core/sinkhorn.py", line 532, in _sinkhorn_iterations_taped
    f, g, errors = _sinkhorn_iterations(tau_a, tau_b, inner_iterations,
  File "/home/usergpu/anaconda3/envs/jax_ott_latest/lib/python3.8/site-packages/ott/core/sinkhorn.py", line 502, in _sinkhorn_iterations
    errors, f_u, g_v = fix_point(
  File "/home/usergpu/anaconda3/envs/jax_ott_latest/lib/python3.8/site-packages/ott/core/fixed_point_loop.py", line 70, in fixpoint_iter
    _, state = jax.lax.while_loop(max_cond_fn, unrolled_body_fn, (0, state))
jax._src.source_info_util.JaxStackTraceBeforeTransformation: ValueError: Reverse-mode differentiation does not work for lax.while_loop or lax.fori_loop. Try using lax.scan instead.

**Comment by marcocuturicameto** [comment]
Hi Effrosyni,
thanks for sharing! I am not sure why this is happening, but I am happy to investigate! 

BTW, if you are only computing the grad, using `implicit_differentiation=True` and `use_danskin=True` is  what is defined by default (if `use_danskin` is not specified, then it defaults to `implicit_differentiation` which is `True` by default). As you mentioned it seems to work on this [colab](https://colab.research.google.com/drive/14aYB4-PmL0kb08tN6e5N9n_0RPR4LpzJ?usp=sharing). Is that a problem? or do you get issues when trying to differentiate again?

**Comment by marcocuturi** [comment]
Thanks for the additional context. I understand better what you want to do. In this case I am not really sure, given the skeleton that you provided, that `implicit_differentiation=True` and `use_danskin=True` will really work in all cases.

I am preparing an update to allow to "force" using a scan. Basically this will be possible by setting `min_iterations` to `max_iterations`. We'll see if that helps. This should be ready by tomorrow.

Thanks for your comments!

**Comment by ersisimou** [comment]
Great, many thanks!

**Comment by marcocuturi** [comment]
The latest release should allow you to switch to a scan. I haven't tested it on your example though.

**Comment by ersisimou** [comment]
I quickly checked my example on the colab you shared yesterday and it always runs with no error.
@marcocuturi many thanks for this toolbox and for your super-fast feedback!

**Comment by marcocuturi** [comment]
Great! thanks again for bearing with us :)
